#!/usr/bin/env python3
"""
Regenerate data.js — the embedded datasets behind the static dashboard.

The dashboard is fully static (GitHub Pages): every page renders whatever is
in `data.js`. This script rebuilds ALL of it from the bot's own outputs, so
the site always shows the truth as of the last run:

  CSV-backed datasets (one per CSV the bot writes):
    sweep_results    <- sweep/results.csv        (offline tournament leaderboard)
    live_summary     <- sweep/live_summary.csv   (current live ranking)
    accounts         <- sweep/accounts.csv       (the 500-strategy grid)
    trades           <- backtest_trades.csv      (last backtest's round trips)
    backtest_results <- backtest_results.csv     (signal strategy vs HODL)
    top10_equity     <- sweep/equity_top10.csv   (top-10 equity curves)
    backtest_equity  <- backtest_equity.csv      (backtest equity curve)

  Built from the per-account audit logs (sweep/accounts/acc_XXX/trades.csv):
    live_trades      — every paper fill across all 500 tournament accounts,
                       flattened with the account id (oldest first; the UI
                       sorts newest-first by default).
    last_trades      — the single most recent fill for each account (the
                       "last trade" per bot), newest first.

  Built from the bot's heartbeat (state/last_run.json):
    bot_status       — WHEN the bot last ran + how it went; rendered as the
                       "Last bot run" badge in every page header.

Usage:
    python3 build_data_js.py             # rebuild data.js
    python3 build_data_js.py --check     # report counts, write nothing

The output file is fully owned by this script — never edit data.js by hand.
"""

import argparse
import csv
import glob
import json
import os
import re
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA_JS = os.path.join(ROOT, "data.js")
ACCOUNT_DIR = os.path.join(ROOT, "sweep", "accounts")
LAST_RUN_FILE = os.path.join(ROOT, "state", "last_run.json")

# JS dataset name -> source CSV (relative to the repo root). A missing CSV
# simply omits that dataset (e.g. no backtest has been run yet).
CSV_DATASETS = [
    ("sweep_results", os.path.join("sweep", "results.csv")),
    ("live_summary", os.path.join("sweep", "live_summary.csv")),
    ("accounts", os.path.join("sweep", "accounts.csv")),
    ("trades", "backtest_trades.csv"),
    ("backtest_results", "backtest_results.csv"),
    ("top10_equity", os.path.join("sweep", "equity_top10.csv")),
    ("backtest_equity", "backtest_equity.csv"),
]

FILE_HEADER = """// CrytpTrde Embedded Datasets
// AUTO-GENERATED by build_data_js.py from the bot's CSV outputs + heartbeat.
// Do not edit by hand — run `python3 build_data_js.py` to regenerate.
window.DATA_SETS = {
"""


def _coerce(value):
    """CSV cells are strings; restore number types the dashboard expects."""
    s = (value or "").strip()
    if not s:
        return ""
    if re.fullmatch(r"[+-]?\d+", s):
        return int(s)
    try:
        return float(s)
    except ValueError:
        return s


def load_csv_dataset(rel_path):
    """Read one of the bot's CSVs into a list of typed row-dicts."""
    path = os.path.join(ROOT, rel_path)
    if not os.path.exists(path):
        return None
    with open(path, newline="", encoding="utf-8") as fh:
        return [{k: _coerce(v) for k, v in row.items()} for row in csv.DictReader(fh)]


def _num(value):
    value = (value or "").strip()
    return float(value) if value else 0.0


def load_trades():
    """Flatten every account's trades.csv into one row per fill.

    Returns ``(rows, last_trades)``:
      * ``rows``        — every fill, oldest first (global order).
      * ``last_trades`` — the most recent fill per account, newest first.
    """
    rows = []
    last = {}
    for path in sorted(glob.glob(os.path.join(ACCOUNT_DIR, "*", "trades.csv"))):
        account = os.path.basename(os.path.dirname(path))
        with open(path, newline="", encoding="utf-8") as fh:
            for row in csv.DictReader(fh):
                record = {
                    "account": account,
                    "timestamp_utc": (row.get("timestamp_utc") or "").strip(),
                    "asset": (row.get("asset") or "").strip(),
                    "side": (row.get("side") or "").strip(),
                    "price_inr": round(_num(row.get("price_inr")), 6),
                    "quantity": round(_num(row.get("quantity")), 8),
                    "notional_inr": round(_num(row.get("notional_inr")), 2),
                    "fee_inr": round(_num(row.get("fee_inr")), 2),
                    "tds_inr": round(_num(row.get("tds_inr")), 2),
                    "realized_pnl_inr": round(_num(row.get("realized_pnl_inr")), 2),
                }
                rows.append(record)

                # trades.csv is append-only, so the last row with the latest
                # timestamp is the true "last trade" (ties = same-cycle fills
                # resolved by file order via `>=`).
                current = last.get(account)
                if current is None or record["timestamp_utc"] >= current["timestamp_utc"]:
                    last[account] = record

    rows.sort(key=lambda r: (r["timestamp_utc"], r["account"], r["asset"], r["side"]))
    last_list = sorted(
        last.values(),
        key=lambda r: (r["timestamp_utc"], r["account"]),
        reverse=True,
    )
    return rows, last_list


def load_bot_status():
    """Read the bot's last-run heartbeat (state/last_run.json).

    cryptobot.py rewrites this file on every command, so it is the true
    answer to "when did the bot last run?". Returns {} when the file is
    missing or unreadable (e.g. a checkout from before the heartbeat
    existed) — the dashboard then falls back to the newest-trade timestamp.
    """
    try:
        with open(LAST_RUN_FILE, encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) and data.get("timestamp_utc") else {}


def build_bot_status(last_trades):
    """Assemble the `bot_status` object embedded in data.js.

    Prefers the real heartbeat (state/last_run.json). If it doesn't exist
    yet, falls back to the newest trade across all accounts, which at least
    proves the bot ran by then. Also stamps `data_generated_utc` so the
    dashboard can tell viewers how fresh this data.js snapshot itself is.
    """
    status = load_bot_status()
    if not status and last_trades:
        newest = last_trades[0]
        status = {
            "timestamp_utc": newest["timestamp_utc"],
            "command": "sweep-live",
            "status": "ok",
            "runner": "unknown",
            "inferred": True,
            "note": "No heartbeat file yet; inferred from the newest trade.",
        }
    status["data_generated_utc"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    return status


def _js_block(name, data):
    body = json.dumps(data, indent=2, ensure_ascii=False)
    body = "\n".join(("  " + ln) if ln else ln for ln in body.split("\n"))
    body = body.lstrip()
    return f'  "{name}": {body}'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="report counts without writing data.js")
    args = parser.parse_args()

    blocks = {}

    for name, rel_path in CSV_DATASETS:
        rows = load_csv_dataset(rel_path)
        if rows is None:
            print(f"{name:<16}: SKIP ({rel_path} not found)")
            continue
        blocks[name] = rows
        print(f"{name:<16}: {len(rows):,} rows  <- {rel_path}")

    live, last = load_trades()
    blocks["live_trades"] = live
    blocks["last_trades"] = last
    bot_status = build_bot_status(last)

    print(f"{'live_trades':<16}: {len(live):,} fills across the tournament accounts")
    print(f"{'last_trades':<16}: {len(last):,} rows (one latest trade per bot)")
    if bot_status.get("inferred"):
        print("bot_status      : inferred (no state/last_run.json yet) from newest trade")
    else:
        print(f"bot_status      : last run {bot_status.get('timestamp_utc')} "
              f"({bot_status.get('command')}, {bot_status.get('status')})")
    if last:
        newest = last[0]
        print("newest fill     :", newest["account"], newest["timestamp_utc"],
              newest["side"], newest["asset"],
              f"pnl=₹{newest['realized_pnl_inr']:,.2f}")

    if args.check:
        return

    # Emission order: bot_status first (the dashboard badge reads it before
    # anything else), then the CSV datasets, then the flattened trade feeds.
    ordered = ["bot_status"] + [n for n, _ in CSV_DATASETS if n in blocks] \
        + ["live_trades", "last_trades"]
    content = FILE_HEADER + ",\n".join(
        _js_block(name, bot_status if name == "bot_status" else blocks[name])
        for name in ordered
    ) + "\n};\n"

    with open(DATA_JS, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"wrote {DATA_JS} ({len(content.encode('utf-8'))/1024:.0f} KiB)")


if __name__ == "__main__":
    main()
